# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eQV6x6-pRiGHDy7M8LjJMr_VQhq9Hxm-
"""

class Rectangle :

    n_edges = 4
    
    def __init__(self, length, width):
      self.length = length
      self.width = width

    def area(self):
      self.area = self.length * self.width
      return self.area 


class Patch(object) :
    def __init__(self, object):
      self.object = object
      self.max = self.object.area()
      self.patch = 0

    def __iter__(self):
      return self
    
    def __next__(self):
      if self.patch >= self.max:
        raise StopIteration
      else:
        self.patch += 1
        self.x = ((self.patch-1)//self.object.width) + 1
        self.y = self.patch - ((self.x-1)*self.object.width)
        return list((self.x,self.y))